# Statistical Hypothesis Testing
In this notebook I:
1. Define the research question and the null and alternative hypotheses.
2. Perform one-way ANOVA tests for all performance variables selected.
3. Explain why I use one-way ANOVA.
4. Evaluate the statistical significance of the results using a significance level of α = 0.05.
5. Interpret the results.

## Loading Libraries

In [1]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm as anova

## Research Question
**Is the AI adoption level of global tech and AI startups associated with stronger financial performance and better operational metrics?**

## Null and Alternative Hypotheses for ANOVA
**H₀**: The mean of the performance variable is equal across all AI adoption levels.

**H₁**: At least one AI adoption level has a different mean for the performance variable.

## Why ANOVA?

ANOVA (Analysis of Variance) is a statistical test used to determine the differences in the mean of a quantitative variable across three or more groups. In this case, I need to compare quantitative variables (the financial performance and operational metrics) across four AI adoption levels (No AI adoption, Low, Medium and High). Since the mean is a suitable statistical measure to compare the performance of each variable across the different levels, I decided to use ANOVA.

A one-way ANOVA will be used to analyze each quantitative variable. If the difference for the variable *x* is statistically significant, I will have evidence to suggest that there is a difference in performance among the various levels of AI adoption, so I will identify which levels differ from each other using Tukey’s HSD test. If there is no statistically significant difference, then I will not have sufficient evidence to suggest that the level of AI adoption is associated with the startups' performance.

## Loading the clean dataset

In [2]:
data = pd.read_csv("global_tech_startups_cleaned.csv")

## Creating the key variables

In [3]:
# Selection of the quantitative key variables
performance_variables = [
    'Revenue_ARR_Millions',
    'Valuation_USD_Millions',
    'Total_Funding_USD_Millions',
    'Layoffs_2024_2025',
    'Current_Headcount_2026',
    'Runway_Months_2024'
]

In [4]:
# for each variable, the model and the if/else statements will be tested
for variable in performance_variables:
    # ANOVA model
    model = ols(f'{variable} ~ C(AI_Adoption_Level)', data = data).fit()

    # ANOVA table
    anova_table = anova(model, typ = 2)

    print(variable)
    display(anova_table)

    # Identification of PR(>F)
    p_value = anova_table.loc['C(AI_Adoption_Level)', 'PR(>F)']

    # if/else statements to determine if H₀ is rejected or not
    if p_value < 0.05:
        print('Reject H₀' + '\n' + '__________________________________________________________')
    else:
        print('Fail to reject H₀' + '\n' + '__________________________________________________________')

    print()

Revenue_ARR_Millions

                            sum_sq       df         F    PR(>F)
C(AI_Adoption_Level)  5.218028e+04      3.0  0.897073  0.441737
Residual              4.846494e+08  24996.0       NaN       NaN

Fail to reject H₀
__________________________________________________________

Valuation_USD_Millions

                            sum_sq       df         F   PR(>F)
C(AI_Adoption_Level)  1.779805e+07      3.0  1.877058  0.13103
Residual              7.900308e+10  24996.0       NaN      NaN

Fail to reject H₀
__________________________________________________________

Total_Funding_USD_Millions

                            sum_sq       df         F    PR(>F)
C(AI_Adoption_Level)  2.176368e+05      3.0  1.665305  0.172126
Residual              1.088899e+09  24996.0       NaN       NaN

Fail to reject H₀
__________________________________________________________

Layoffs_2024_2025

                            sum_sq       df        F    PR(>F)
C(AI_Adoption_Level)  1.013860e+05      3.0  1.09118  0.351363
Residual              7.741604e+08  24996.0      NaN       NaN

Fail to reject H₀
__________________________________________________________

Current_Headcount_2026

                            sum_sq       df         F    PR(>F)
C(AI_Adoption_Level)  1.914529e+06      3.0  1.736937  0.157025
Residual              9.183903e+09  24996.0       NaN       NaN

Fail to reject H₀
__________________________________________________________

Runway_Months_2024

                            sum_sq       df         F    PR(>F)
C(AI_Adoption_Level)  2.731504e+02      3.0  0.892551  0.444054
Residual              2.549870e+06  24996.0       NaN       NaN

Fail to reject H₀
__________________________________________________________

## Interpretation

Since the p-values for all the performance variables are greater than the significance level (α = 0.05), there is not enough evidence to reject the null hypothesis. None of the variables show a statistically significant difference across AI adoption levels.

Therefore, there is not enough evidence to believe that the AI adoption level of global tech and AI startups is associated with their performance.

Because there were no significant differences, Tukey HSD was not necessary.